# -*- coding: utf-8 -*-
"""Copy of simple_linear_regression.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mJCrofOVDQ6HeaJjSOq_R97FANDEOjsC

# Simple Linear Regression

## Importing the libraries
"""

import numpy as nm
import pandas as pd
import matplotlib.pyplot as plt

"""## Importing the dataset"""

DATA = pd.read_csv("./Salary_Data.csv")
DATA
X = DATA.iloc[:,:-1]
y = DATA.iloc[:,-1:]
print(X)
print(y)

"""## Splitting the dataset into the Training set and Test set"""

from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3,random_state=0)

"""## Training the Simple Linear Regression model on the Training set"""

from sklearn.linear_model import LinearRegression
reg = LinearRegression()
reg.fit(X_test,y_test)

"""## Predicting the Test set results"""

y_pred = reg.predict(X_test)

"""## Visualising the Training set results"""

plt.scatter(X_test, y_test, color = 'red')
plt.plot(X_test,reg.predict(X_test),color="black")
plt.title('Salary vs Experience (Training set)')
plt.xlabel('Years of Experience')
plt.ylabel('Salary')
plt.show()

plt.scatter(X_train, y_train, color = 'blue')
plt.plot(X_train,reg.predict(X_train),color="black")
plt.title('Salary vs Experience (Training set)')
plt.xlabel('Years of Experience')
plt.ylabel('Salary')
plt.show()

"""## Visualising the Test set results"""